# To print current variables for reference
# tmux show-options -g
#
#
# Starts Here
set -sg escape-time 100 #Ghostty needs this. remove if u want responsive typing.
set -as terminal-features ",xterm-256color:RGB"
set -g mouse on
set -g mode-keys vi

# # Increase scrollback history limit (default is 2000)
set -g history-limit 50000

# Start window and pane numbering at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# catppuccin Starts here
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Show Session on the left catppuccin Style
set -g status-left "#{E:@catppuccin_status_session}"
#set -ag status-right "#{E:@catppuccin_status_session}" # Uncomment to be on the right

# make the pill content Window name
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Disable confirmation prompt when killing a pane
bind x kill-pane

# Disable confirmation prompt when killing a window
bind X kill-window

# In case you have a battery like a laptop
# set -agF status-right "#{E:@catppuccin_status_battery}"

# Install these plugins otherwise it wont do anything
# and keep them at the end

run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
